// generated from rosidl_typesupport_introspection_c/resource/idl__rosidl_typesupport_introspection_c.h.em
// with input from dingo_peripheral_interfacing_msg:msg/ElectricalMeasurements.idl
// generated code does not contain a copyright notice

#ifndef DINGO_PERIPHERAL_INTERFACING_MSG__MSG__DETAIL__ELECTRICAL_MEASUREMENTS__ROSIDL_TYPESUPPORT_INTROSPECTION_C_H_
#define DINGO_PERIPHERAL_INTERFACING_MSG__MSG__DETAIL__ELECTRICAL_MEASUREMENTS__ROSIDL_TYPESUPPORT_INTROSPECTION_C_H_

#ifdef __cplusplus
extern "C"
{
#endif


#include "rosidl_runtime_c/message_type_support_struct.h"
#include "rosidl_typesupport_interface/macros.h"
#include "dingo_peripheral_interfacing_msg/msg/rosidl_typesupport_introspection_c__visibility_control.h"

ROSIDL_TYPESUPPORT_INTROSPECTION_C_PUBLIC_dingo_peripheral_interfacing_msg
const rosidl_message_type_support_t *
ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(rosidl_typesupport_introspection_c, dingo_peripheral_interfacing_msg, msg, ElectricalMeasurements)();

#ifdef __cplusplus
}
#endif

#endif  // DINGO_PERIPHERAL_INTERFACING_MSG__MSG__DETAIL__ELECTRICAL_MEASUREMENTS__ROSIDL_TYPESUPPORT_INTROSPECTION_C_H_
